### ISSUE TITLE
Move to travis-ci.com (instead of travis.org)

### ISSUE THREAD

**Issue by NathanFallet** [Kitura/Swift-Kuery-ORM#133]
The old travis.org service is [no longer available](https://blog.travis-ci.com/2021-05-07-orgshutdown).
You need to activate something in order to move the CI to travis-ci.com. PRs won't be able to get merged otherwise

**Comment by mbarnach** [comment]
@NathanFallet Thanks for the reminder. We are currently in the process of doing it, but there is quite a few repos to go through
@dannys42 Do you have any progress on this side?

**Comment by dannys42** [comment]
I'll try to prioritize this in the next couple days.  FYI, part of the process I've been going through is also to update the CI builds to include newer versions of swift and deprecate Swift 4.x.  Let me know if there are any issues with that.

**Comment by dannys42** [comment]
FYI, I'm working on this... Some of the dependencies (e.g. Swift-Kuery and KituraContracts) also need updating, so it's going a little slower than I'd hoped.

**Comment by dannys42** [comment]
Resolved in [PR](https://github.com/Kitura/Swift-Kuery-ORM/pull/134) and release 1.0.0
