### ISSUE TITLE
Anyone using Swift 5?

### ISSUE THREAD

**Issue by arron-rgb** [Kitura/Swift-Kuery-ORM#137]
## Context and Description
When I try to build my project, it returns an error.

<img width="867" alt="Screen Shot 2022-02-28 at 3 11 19 AM" src="https://user-images.githubusercontent.com/64225212/155947465-3efcb2ad-5fe3-42f5-97fb-0ed13e743563.png">

I found it is caused by https://github.com/Kitura/CLibpq/blob/master/Package.swift

### Environment Details
Swift 5.5
Xcode 13.1

### Steps to Reproduce
1) Just followed by this repo's readme

### Expected vs. Actual Behaviour
- [ ] Expected to happen...
build successfully 
- [ ] Actually happened...
cannot run

**Comment by dannys42** [comment]
Just to confirm, is this Swift 5.5?

**Comment by arron-rgb** [comment]
yes swift 5.5

**Comment by dannys42** [comment]
Strange, it should be working.  What version of Swift-Kuery-ORM are you pointing to?  If you're using SPM, can you share your Package.swift file?

**Comment by arron-rgb** [comment]
`// swift-tools-version: 5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "A5",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
      .package(url: "https://github.com/Kitura/Swift-Kuery-ORM.git", from: "1.0.0"),
      .package(url: "https://github.com/Kitura/Swift-Kuery-PostgreSQL.git", from: "2.2.0"),
    ],
    targets: [
    .executableTarget(
            name: "A5",
            dependencies: [.product(name: "SwiftKueryORM", package: "Swift-Kuery-ORM"), .product(name: "SwiftKueryPostgreSQL", package: "Swift-Kuery-PostgreSQL")]
        )
    ]
)
`

**Comment by dannys42** [comment]
Ah, I see. I added the swift-tools-version to CLibpq.  Can you try and see if that works?

**Comment by arron-rgb** [comment]
it works now thanks
